### ISSUE TITLE
首次运行报错

### ISSUE THREAD

**Issue by asing** [ring04h/wydomain#12]
## \* Starting fofa plugin search

Traceback (most recent call last):
  File "wydomain.py", line 346, in <module>
    print start_wydomain(sys.argv[1])
  File "wydomain.py", line 53, in start_wydomain
    fofa_result = start_fofa_plugin(domain)
  File "/Users/user/git/wydomain/fofaplugin.py", line 244, in start_fofa_plugin
    get_partner_domain(domain)
  File "/Users/user/git/wydomain/fofaplugin.py", line 181, in get_partner_domain
    jobId = json.loads(taskinfo)['jobId']
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by cnbeining** [comment]
里面用的获取旁站的站死了。

所以没法修。。。修完了这个脚本也就废了。。。。。

**Comment by asing** [comment]
那就是没法用了？

On Tue, Aug 11, 2015 at 2:52 PM, David Zhuang notifications@github.com
wrote:

> 里面用的获取旁站的站死了。
> 
> 所以没法修。。。修完了这个脚本也就废了。。。。。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ring04h/wydomain/issues/12#issuecomment-129730208.

## 

---

_瘾大技术差_

**Comment by cnbeining** [comment]
除非有人能把那个站重新弄出来。

没钱没精力啊。。

**Comment by chennqqi** [comment]
fofa 暂时关闭了

**Comment by asing** [comment]
好吧 -_-
