### ISSUE TITLE
安装好了报错 TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by dongchi** [ring04h/wydomain#15]
TypeError: 'NoneType' object is not iterable

**Comment by dongchi** [comment]
运行环境debian 32位

**Comment by nexusguardusa** [comment]
Traceback (most recent call last):
  File "wydomain.py", line 346, in <module>
    print start_wydomain(sys.argv[1])
  File "wydomain.py", line 305, in start_wydomain
    subdomains_result = wy_subdomain_run(domain)
  File "/tools/wydomain/wysubdomain.py", line 56, in wy_subdomain_run
    my_subdomains = get_subdomain_run(domain)
  File "/tools/wydomain/mysubdomain.py", line 200, in get_subdomain_run
    mydomains.extend(links_get(domain))
TypeError: 'NoneType' object is not iterable

**Comment by ring04h** [comment]
等新版本更新

**Comment by ring04h** [comment]
https://github.com/ring04h/wydomain  版本更新了。
