### ISSUE TITLE
安装完成后运行报错 ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by JaminZhang** [ring04h/wydomain#16]
```bash
[root@VM_15_187_centos wydomain]# python wydomain.py 163.com 
--------------------------------------------------
* Starting fofa plugin search
--------------------------------------------------
Traceback (most recent call last):
  File "wydomain.py", line 346, in <module>
    print start_wydomain(sys.argv[1])
  File "wydomain.py", line 53, in start_wydomain
    fofa_result = start_fofa_plugin(domain)
  File "/usr/local/wydomain/fofaplugin.py", line 244, in start_fofa_plugin
    get_partner_domain(domain)
  File "/usr/local/wydomain/fofaplugin.py", line 181, in get_partner_domain
    jobId = json.loads(taskinfo)['jobId']
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```    
几个月前运行正常，今天再次安装后运行报如上错误。

#12 和这个报错一样吗？
https://fofa.so/lab/addtask/?taskaction=alldomains&domain=
这个接口不可用了？脚本就不可用了？

**Comment by ring04h** [comment]
新版本其实已经写好了，采用的是每个脚本独立运行输出到json文件，加入了try错误异常控制会稳定很多，过几天发出来。

**Comment by ring04h** [comment]
https://github.com/ring04h/wydomain/tree/wydomain2
