### ISSUE TITLE
python wydomain.py wooyun.org 第一次使用时有点问题 ubuntu 32位系统

### ISSUE THREAD

**Issue by leveryd** [ring04h/wydomain#2]
## \* Starting get ns record
- ns2.dnsv2.com in whitelist
## \* ns1.dnsv2.com in whitelist

---
## \* Starting subdomain search task

Traceback (most recent call last):
  File "wydomain.py", line 337, in <module>
    print start_wydomain(sys.argv[1])
  File "wydomain.py", line 298, in start_wydomain
    subdomains_result = wy_subdomain_run(domain)
  File "/root/wydomain/wysubdomain.py", line 56, in wy_subdomain_run
    my_subdomains = get_subdomain_run(domain)
  File "/root/wydomain/mysubdomain.py", line 200, in get_subdomain_run
    mydomains.extend(links_get(domain))
TypeError: 'NoneType' object is not iterabl

**Comment by ring04h** [comment]
links_get(domain)，返回的结果为Nonetype，你单独用域名跑一下看看什么结果？
python mysubdomain.py domain

**Comment by ring04h** [comment]
https://github.com/ring04h/wydomain/tree/wydomain2
