### ISSUE TITLE
fofa模块貌似跪了

### ISSUE THREAD

**Issue by DogeWatch** [ring04h/wydomain#21]
$ python wydomain.py baidu.com
--------------------------------------------------
* Starting fofa plugin search
--------------------------------------------------
Traceback (most recent call last):
  File "wydomain.py", line 346, in <module>
    print start_wydomain(sys.argv[1])
  File "wydomain.py", line 53, in start_wydomain
    fofa_result = start_fofa_plugin(domain)
  File "/X/X/X/wydomain/fofaplugin.py", line 244, in start_fofa_plugin
    get_partner_domain(domain)
  File "/X/X/X/wydomain/fofaplugin.py", line 181, in get_partner_domain
    jobId = json.loads(taskinfo)['jobId']
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by ring04h** [comment]
换新版啊，你那个是老版本

**Comment by lianfeng30** [comment]
新版地址在哪？ 我这也报错

**Comment by lianfeng30** [comment]
难道是https://github.com/ring04h/wydomain  插件去了？

**Comment by ring04h** [comment]
重新创建目录： git clone https://github.com/ring04h/wydomain
