### ISSUE TITLE
出错。

### ISSUE THREAD

**Issue by sechacking** [ring04h/wydomain#6]
---

Traceback (most recent call last):
  File "wydomain.py", line 346, in <module>
    print start_wydomain(sys.argv[1])
  File "wydomain.py", line 53, in start_wydomain
    fofa_result = start_fofa_plugin(domain)
  File "/home/huang.jinbao/wydomain/fofaplugin.py", line 242, in start_fofa_plugin
    get_partner_domain(domain)
  File "/home/huang.jinbao/wydomain/fofaplugin.py", line 180, in get_partner_domain
    domian_jobInfo_url = 'http://fofa.so/lab/gettask?jobId=%s&t=%s' % (jobId, int(time.time()))
NameError: global name 'time' is not defined

**Comment by sechacking** [comment]
File "/home/huang.jinbao/wydomain/fofaplugin.py", line 186, in get_partner_domain
    partner_result = json.loads(http_request_get(domian_jobInfo_url)['html'])
TypeError: 'Response' object has no attribute '**getitem**'

**Comment by ring04h** [comment]
已解决，git pull 一下更新代码就好了。
