### ISSUE TITLE
http_request_get出错

### ISSUE THREAD

**Issue by sechacking** [ring04h/wydomain#7]
Traceback (most recent call last):
  File "wydomain.py", line 346, in <module>
    print start_wydomain(sys.argv[1])
  File "wydomain.py", line 53, in start_wydomain
    fofa_result = start_fofa_plugin(domain)
  File "/home/huang.jinbao/wydomain/fofaplugin.py", line 243, in start_fofa_plugin
    get_partner_domain(domain)
  File "/home/huang.jinbao/wydomain/fofaplugin.py", line 186, in get_partner_domain
    partner_result = json.loads(http_request_get(domian_jobInfo_url)['html'])
TypeError: 'Response' object has no attribute '**getitem**'

**Comment by 80vul** [comment]
http://fofa.so 突然又复活了，做了一些修改，fofaplugin.py 已更新，可以用了。

**Comment by sechacking** [comment]
good!等会测试下。

**Comment by ring04h** [comment]
#cd wydomain
#git pull
更新下代码就可以了。
